drop  DATABASE CRUD_ESTAPAR;
USE CRUD_ESTAPAR;

CREATE TABLE Manobrista
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(200) NOT NULL,
	Cpf VARCHAR(15) NOT NULL,
	Nascimento DATE NOT NULL
)

CREATE TABLE MarcaCarro
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Marca VARCHAR(100) NOT NULL,
)

CREATE TABLE ModeloCarro
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	IdMarca INT NOT NULL,
	Modelo VARCHAR(100) NOT NULL,
	FOREIGN KEY (IdMarca) REFERENCES MarcaCarro(Id)
)

CREATE TABLE Carro
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	IdModelo INT NOT NULL,
	placa VARCHAR(8) NOT NULL,
	FOREIGN KEY (IdModelo) REFERENCES ModeloCarro(Id)
)

CREATE TABLE Manobra
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	IdCarro INT NOT NULL,
	IdManobrista INT NOT NULL,
	Classificacao BIT NOT NULL,
	Datahora DATETIME NOT NULL,
	FOREIGN KEY (IdCarro) REFERENCES Carro(Id),
	FOREIGN KEY (IdManobrista) REFERENCES Manobrista(Id),
)